name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and Playwright Browsers
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright tests
        id: playwright_tests
        run: |
          npx playwright test
        env:
            EMAIL: ${{ vars.EMAIL }}
            PASSWORD: ${{ secrets.PASSWORD_CLV }}
            BASE_URL: ${{ vars.BASEURL }}
            ROOMNAME: ${{ vars.ROOMNAME }}
        continue-on-error: false
